name: CI/CD Workflow

on:
  push:
    branches:
      - develop

concurrency: production_environment

jobs:
    build-js-production:
        name: Build for Staging Server
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop'
        steps:
            - uses: actions/checkout@v1
            - name: Composer install
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    deploy-production:
        name: Deploy Project to Staging Server
        runs-on: ubuntu-latest
        needs: [build-js-production]
        if: github.ref == 'refs/heads/develop'
        steps:
            - uses: actions/checkout@v1
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: '8.1'
                  extensions: mbstring, bcmath, curl
            - name: Composer install
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --verbose
            - name: Setup Deployer
              uses: atymic/deployer-php-action@master
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
            - name: Deploy to Production
              env:
                  DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
              run: php vendor/bin/dep deploy staging --branch="develop" -vvv
